import {
  ArrowClockwise,
  ArrowLeft,
  Bank,
  CalendarCheck,
  CaretDown,
  CashRegister,
  ChartLineUp,
  CheckCircle,
  Clock,
  Coins,
  DesktopTower,
  FileText,
  GearSix,
  ListChecks,
  MagnifyingGlass,
  MapPin,
  Package,
  Receipt,
  ShieldCheck,
  SignOut,
  SquaresFour,
  Storefront,
  Table,
  UserCircle,
  UsersThree,
  WarningCircle,
  X,
} from "@phosphor-icons/react";

export {
  operationalIconNames,
  operationalIconSizes,
  operationalIconWeights,
} from "./role-icon-config";
export type { OperationalIconName } from "./role-icon-config";

export const operationalIcons = {
  accounting: Bank,
  approvals: ShieldCheck,
  back: ArrowLeft,
  branch: Storefront,
  caretDown: CaretDown,
  cashierQueue: ListChecks,
  cashierReceipts: Receipt,
  cashierTill: CashRegister,
  close: X,
  floor: SquaresFour,
  inventory: Package,
  logout: SignOut,
  me: UserCircle,
  operations: ListChecks,
  overview: ChartLineUp,
  refresh: ArrowClockwise,
  reports: FileText,
  reservations: CalendarCheck,
  revenue: Coins,
  search: MagnifyingGlass,
  serviceArea: MapPin,
  settings: GearSix,
  staff: UsersThree,
  success: CheckCircle,
  table: Table,
  time: Clock,
  warning: WarningCircle,
  workstation: DesktopTower,
} as const;
