-- M20.1: Reporting Depth Expansion
-- Expand ReportType enum with additional report types

ALTER TYPE "ReportType" ADD VALUE 'SALES_BY_CATEGORY';
ALTER TYPE "ReportType" ADD VALUE 'SALES_BY_HOUR';
ALTER TYPE "ReportType" ADD VALUE 'DISCOUNTS_SUMMARY';
ALTER TYPE "ReportType" ADD VALUE 'VOIDS_SUMMARY';
ALTER TYPE "ReportType" ADD VALUE 'REFUNDS_SUMMARY';
ALTER TYPE "ReportType" ADD VALUE 'CASH_VARIANCE';
ALTER TYPE "ReportType" ADD VALUE 'CASH_MOVEMENTS';
ALTER TYPE "ReportType" ADD VALUE 'WASTAGE_SUMMARY';
ALTER TYPE "ReportType" ADD VALUE 'LOW_STOCK';
ALTER TYPE "ReportType" ADD VALUE 'RESERVATION_DEPOSITS';
ALTER TYPE "ReportType" ADD VALUE 'RESERVATION_NO_SHOWS';
ALTER TYPE "ReportType" ADD VALUE 'EVENT_BOOKINGS';
ALTER TYPE "ReportType" ADD VALUE 'EVENT_CHECKINS';
ALTER TYPE "ReportType" ADD VALUE 'STAFF_OPERATIONS';
ALTER TYPE "ReportType" ADD VALUE 'HIGH_RISK_ACTORS';
ALTER TYPE "ReportType" ADD VALUE 'OPEN_CLOSED_ORDERS';
ALTER TYPE "ReportType" ADD VALUE 'REPORT_CATALOG';
